"""Add new model

Revision ID: 0e5dc3e28f17
Revises: 196c3f16ff09
Create Date: 2025-07-17 20:28:56.053900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e5dc3e28f17'
down_revision: Union[str, Sequence[str], None] = '196c3f16ff09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_contenido', sa.Uuid(), nullable=False),
    sa.Column('id_archivo', sa.BigInteger(), nullable=False),
    sa.Column('fecha_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('referencia_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombre_receptor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero_documento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banco_origen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cuenta_origen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banco_destino', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cuenta_destino', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medio_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concepto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explicacion_score', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_contenido'], ['logs.id_contenido'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_id_contenido'), 'pago', ['id_contenido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_id_contenido'), table_name='pago')
    op.drop_table('pago')
    # ### end Alembic commands ###
