"""Fix: Extract columns

Revision ID: 44796a6287d0
Revises: 52fe44ff7f75
Create Date: 2025-07-30 00:55:20.310035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44796a6287d0'
down_revision: Union[str, Sequence[str], None] = '52fe44ff7f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracto_bancario_encargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extract_id', sa.Uuid(), nullable=False),
    sa.Column('numero_encargo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_encargo', sa.DateTime(), nullable=True),
    sa.Column('valor_encargo', sa.Float(), nullable=True),
    sa.Column('concepto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['extract_id'], ['extracto_bancario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracto_bancario_id_contenido'), 'extracto_bancario', ['id_contenido'], unique=False)
    op.add_column('extracto_bancario_movimientos', sa.Column('assignment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'extracto_bancario_movimientos', 'extracto_bancario', ['extract_id'], ['id'])
    op.create_foreign_key(None, 'extracto_bancario_movimientos', 'extracto_bancario_encargos', ['assignment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extracto_bancario_movimientos', type_='foreignkey')
    op.drop_constraint(None, 'extracto_bancario_movimientos', type_='foreignkey')
    op.drop_column('extracto_bancario_movimientos', 'assignment_id')
    op.drop_index(op.f('ix_extracto_bancario_id_contenido'), table_name='extracto_bancario')
    op.drop_table('extracto_bancario_encargos')
    # ### end Alembic commands ###
