"""Add new model

Revision ID: 7922a0857e9b
Revises: 9a4f997207cd
Create Date: 2025-07-21 13:54:21.247968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7922a0857e9b'
down_revision: Union[str, Sequence[str], None] = '9a4f997207cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_contenido', sa.Uuid(), nullable=False),
    sa.Column('id_archivo', sa.BigInteger(), nullable=False),
    sa.Column('nombre_banco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_nit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombre_titular', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_saldos', sa.DateTime(), nullable=True),
    sa.Column('saldo_total_encargos', sa.Float(), nullable=True),
    sa.Column('saldo_canje_encargos', sa.Float(), nullable=True),
    sa.Column('saldo_disponible_encargos', sa.Float(), nullable=True),
    sa.Column('saldo_total_cuentas', sa.Float(), nullable=True),
    sa.Column('saldo_canje_cuentas', sa.Float(), nullable=True),
    sa.Column('saldo_disponible_cuentas', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explicacion_score', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_contenido'], ['logs.id_contenido'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saldo_id_contenido'), 'saldo', ['id_contenido'], unique=False)
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance_id', sa.Uuid(), nullable=False),
    sa.Column('numero_cuenta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombre_banco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saldo_total', sa.Float(), nullable=True),
    sa.Column('saldo_canje', sa.Float(), nullable=True),
    sa.Column('saldo_disponible', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['balance_id'], ['saldo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_proyecto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero_encargo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombre_fondo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saldo_total', sa.Float(), nullable=True),
    sa.Column('saldo_canje', sa.Float(), nullable=True),
    sa.Column('saldo_disponible', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['balance_id'], ['saldo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden')
    op.drop_table('cuenta')
    op.drop_index(op.f('ix_saldo_id_contenido'), table_name='saldo')
    op.drop_table('saldo')
    # ### end Alembic commands ###
