"""Add new model

Revision ID: 905fe5985a7e
Revises: 7922a0857e9b
Create Date: 2025-07-21 16:33:00.809098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905fe5985a7e'
down_revision: Union[str, Sequence[str], None] = '7922a0857e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuenta', sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cuenta', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cuenta', sa.Column('total_balance', sa.Float(), nullable=True))
    op.drop_column('cuenta', 'saldo_total')
    op.drop_column('cuenta', 'saldo_canje')
    op.drop_column('cuenta', 'nombre_banco')
    op.drop_column('cuenta', 'numero_cuenta')
    op.add_column('orden', sa.Column('proyect_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orden', sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orden', sa.Column('fund_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orden', sa.Column('total_balance', sa.Float(), nullable=True))
    op.add_column('orden', sa.Column('exchange_balance', sa.Float(), nullable=True))
    op.add_column('orden', sa.Column('available_balance', sa.Float(), nullable=True))
    op.drop_column('orden', 'nombre_proyecto')
    op.drop_column('orden', 'saldo_canje')
    op.drop_column('orden', 'numero_encargo')
    op.drop_column('orden', 'saldo_total')
    op.drop_column('orden', 'saldo_disponible')
    op.drop_column('orden', 'nombre_fondo')
    op.add_column('saldo', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('saldo', sa.Column('account_holder', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('saldo', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('saldo', sa.Column('balance_date', sa.DateTime(), nullable=True))
    op.add_column('saldo', sa.Column('total_orders', sa.Float(), nullable=True))
    op.add_column('saldo', sa.Column('total_orders_exchange', sa.Float(), nullable=True))
    op.add_column('saldo', sa.Column('total_orders_available', sa.Float(), nullable=True))
    op.add_column('saldo', sa.Column('total_accounts', sa.Float(), nullable=True))
    op.add_column('saldo', sa.Column('total_accounts_exchange', sa.Float(), nullable=True))
    op.add_column('saldo', sa.Column('total_accounts_available', sa.Float(), nullable=True))
    op.drop_column('saldo', 'saldo_total_encargos')
    op.drop_column('saldo', 'saldo_canje_encargos')
    op.drop_column('saldo', 'saldo_canje_cuentas')
    op.drop_column('saldo', 'saldo_disponible_encargos')
    op.drop_column('saldo', 'nombre_banco')
    op.drop_column('saldo', 'moneda')
    op.drop_column('saldo', 'saldo_disponible_cuentas')
    op.drop_column('saldo', 'nombre_titular')
    op.drop_column('saldo', 'saldo_total_cuentas')
    op.drop_column('saldo', 'fecha_saldos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saldo', sa.Column('fecha_saldos', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('saldo_total_cuentas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('nombre_titular', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('saldo_disponible_cuentas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('moneda', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('nombre_banco', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('saldo_disponible_encargos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('saldo_canje_cuentas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('saldo_canje_encargos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('saldo', sa.Column('saldo_total_encargos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('saldo', 'total_accounts_available')
    op.drop_column('saldo', 'total_accounts_exchange')
    op.drop_column('saldo', 'total_accounts')
    op.drop_column('saldo', 'total_orders_available')
    op.drop_column('saldo', 'total_orders_exchange')
    op.drop_column('saldo', 'total_orders')
    op.drop_column('saldo', 'balance_date')
    op.drop_column('saldo', 'currency')
    op.drop_column('saldo', 'account_holder')
    op.drop_column('saldo', 'bank_name')
    op.add_column('orden', sa.Column('nombre_fondo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orden', sa.Column('saldo_disponible', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orden', sa.Column('saldo_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orden', sa.Column('numero_encargo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orden', sa.Column('saldo_canje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orden', sa.Column('nombre_proyecto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orden', 'available_balance')
    op.drop_column('orden', 'exchange_balance')
    op.drop_column('orden', 'total_balance')
    op.drop_column('orden', 'fund_name')
    op.drop_column('orden', 'order_number')
    op.drop_column('orden', 'proyect_name')
    op.add_column('cuenta', sa.Column('numero_cuenta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cuenta', sa.Column('nombre_banco', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cuenta', sa.Column('saldo_canje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cuenta', sa.Column('saldo_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('cuenta', 'total_balance')
    op.drop_column('cuenta', 'bank_name')
    op.drop_column('cuenta', 'account_number')
    # ### end Alembic commands ###
