"""Add new model validation error

Revision ID: 9a4f997207cd
Revises: e32704de6abf
Create Date: 2025-07-21 20:11:27.364998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a4f997207cd'
down_revision: Union[str, Sequence[str], None] = 'e32704de6abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_error',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_contenido', sa.Uuid(), nullable=False),
    sa.Column('check_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id_contenido'], ['logs.id_contenido'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_error_id_contenido'), 'validation_error', ['id_contenido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_error_id_contenido'), table_name='validation_error')
    op.drop_table('validation_error')
    # ### end Alembic commands ###
