"""Add new model

Revision ID: e32704de6abf
Revises: 0e5dc3e28f17
Create Date: 2025-07-18 14:56:12.578893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e32704de6abf'
down_revision: Union[str, Sequence[str], None] = '0e5dc3e28f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_contenido', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explicacion_score', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_contenido'], ['logs.id_contenido'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_id_contenido'), 'email', ['id_contenido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_id_contenido'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
